### Модели
## Создание модели
POST http://localhost:8080/api/v1/models
Content-Type: application/json
Cookie: JSESSIONID=544566F76F3CFE68300E6CF359795194

{
  "name": "GPT-4",
  "description": "Продвинутая языковая модель",
  "modelType": "EXTERNAL",
  "provider": "OPENAI",
  "apiEndpoint": "https://api.openai.com/v1/chat/completions",
  "apiToken": "sk-xxx",
  "maxTokens": 8000,
  "temperature": 0.7
}

### Обновление модели
PUT http://localhost:8080/api/v1/models/1
Content-Type: application/json

{
  "name": "GPT-4 Turbo",
  "maxTokens": 16000,
  "temperature": 0.8
}

### Получение всех моделей
GET http://localhost:8080/api/models
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbGVrcyIsImlhdCI6MTczODgyNTIxOSwiZXhwIjoxNzQwMDM0ODE5fQ.3NJDT9c1wRPk9PiAa8YHlSrkPYmbPscRK5GGSSkT3ZModXAPzo6OIK8M7GzAEIQEXYHOnBjitvN7YxnKbLpiPg


### Удаление модели
DELETE http://localhost:8080/api/v1/models/1
